global:
  # How frequently to scrape targets by default.
  scrape_interval: 60s

  # How long until a scrape request times out.
  scrape_timeout: 10s
# A list of scrape configurations.
scrape_configs:
  - job_name: 'exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: prometheus
    metrics_path: /prom/metrics
    static_configs:
      - targets:
          - localhost:9090 # prometheus endpoint address
  - job_name: golang
    metrics_path: /metrics
    static_configs:
      - targets:
          - golang:8080 # prometheus endpoint address