{
 "title": "Metrics demo - imported",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "le",
    "query": {
     "query": "label_values(working_time_bucket,le)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(lang, langVersion) (irate(working_time_count[$__interval]))",
     "legendFormat": "{{lang}}:{{langVersion}}"
    }
   ]
  },
  {
   "title": "Requests last hour",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(lang, langVersion) (increase(working_time_count[1h]))",
     "legendFormat": "{{lang}}:{{langVersion}}"
    }
   ]
  },
  {
   "title": "Requests that emimited le < $le",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "le",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(working_time_bucket{le=~\"$le\"}[1m])) by (lang, langVersion) / sum(rate(working_time_bucket{le=\"+Inf\"}[1m])) by (lang, langVersion)",
     "legendFormat": "{{lang}}:{{langVersion}}"
    }
   ]
  }
 ]
}